spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: demo
    password: D3m0
  jpa:
    show-sql: true
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect